---
- name: Setup application environment on Oracle Linux
  hosts: webservers
  become: yes
  vars:
    java_version: "1.8.0"
    maven_version: "3.6.3"
    git_repo: "https://github.com/Onadelyer/lavagna.git"
    project_dir: "/opt/lavagna"

  tasks:
    - name: Install Java 8
      yum:
        name: "java-{{ java_version }}-openjdk-devel"
        state: present

    - name: Download Maven
      get_url:
        url: "https://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"

    - name: Extract Maven
      unarchive:
        src: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Maven Path
      shell: 'echo "export PATH=/opt/apache-maven-{{ maven_version }}/bin:$PATH" >> ~/.bashrc'
      args:
        executable: /bin/bash
      become: yes


    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone application repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ project_dir }}"
        clone: yes
        update: yes

    - name: Build the application with Maven
      shell: /opt/apache-maven-{{ maven_version }}/bin/mvn package
      args:
        chdir: "{{ project_dir }}"

    # - name: Deploy the application
    #   shell: nohup java -Ddatasource.dialect=PGSQL -Ddatasource.url=jdbc:postgresql://localhost:5432/lavagna -Ddatasource.username=myuser -Ddatasource.password=mypassword -Dspring.profile.active=dev -jar {{ project_dir }}/target/lavagna-jetty-console.war > /dev/null 2>&1 &
    #   async: 10
    #   poll: 0