---
- name: Setup PostgreSQL Database
  hosts: webservers
  become: yes
  vars:
    postgresql_databases:
      - name: lavagna
    postgresql_users:
      - name: myuser
        password: mypassword
  roles:
    - role: geerlingguy.postgresql
