---
- name: Setup PostgreSQL Database
  hosts: webservers
  become: yes
  vars:
    postgresql_databases:
      - name: lavagna
    postgresql_users:
      - name: myuser
        password: mypassword
    postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
      - { type: host, database: all, user: myuser, address: 'all', auth_method: md5 }

  roles:
    - role: geerlingguy.postgresql

  tasks:
    - name: Ensure the unaccent extension is created in the lavagna database
      become: yes
      become_user: postgres
      postgresql_ext:
        name: unaccent
        db: lavagna

    - name: Grant CREATE on database to myuser (necessary to create extensions, etc.)
      become: yes
      become_user: postgres
      postgresql_privs:
        db: lavagna
        role: myuser
        objs: ALL_IN_SCHEMA
        privs: ALL
        type: database

    - name: Optionally, grant myuser superuser privileges (use with caution)
      become: yes
      become_user: postgres
      postgresql_user:
        name: myuser
        role_attr_flags: SUPERUSER
