---
- name: Setup PostgreSQL Database
  hosts: webservers
  become: yes
  vars:
    postgresql_databases:
      - name: lavagna
    postgresql_users:
      - name: myuser
        password: mypassword
    postgresql_user_privileges:
      - name: myuser
        db: lavagna
        priv: "ALL"
        role_attr_flags: SUPERUSER

  roles:
    - role: geerlingguy.postgresql

  tasks:
    - name: Ensure the unaccent extension is created in the lavagna database
      postgresql_ext:
        db: lavagna
        name: unaccent
        state: present
      become: yes
      become_user: postgres
