---
- name: Install and configure Apache Tomcat
  hosts: webservers
  become: true
  vars:
    tomcat_version: "9.0.41" # Вы можете изменить на любую поддерживаемую версию
    tomcat_install_java: True
    tomcat_java_version: "1.8" # Установка OpenJDK Java версии 8
    tomcat_install_path: "/opt/tomcat" # Путь установки Tomcat
    tomcat_jvm_memory_percentage_xms: 15 # Начальный размер кучи JVM как процент от общей системной памяти
    tomcat_jvm_memory_percentage_xmx: 55 # Максимальный размер кучи JVM
    tomcat_allow_manager_access_only_from_localhost: False
    tomcat_allow_host_manager_access_only_from_localhost: False
    tomcat_users: # Определение пользователей Tomcat и их ролей
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "exampleuser"
        password: "us3rp@ssw0rd"
        roles: "tomcat"
    tomcat_permissions_production: True
    tomcat_webapps_auto_deployment: True
    tomcat_permissions_ensure_on_every_run: True
    tomcat_prod_modes:
      - ['bin', '2750', '0640']
      - ['conf', '2750', '0640']
      - ['lib', '2750', '0640']
      - ['logs', '0300', '0640']
      - ['temp', '0750', '0640']
      - ['work', '0750', '0640']
      - ['webapps', '0750', '0640']
    tomcat_port_connector: 8080
    tomcat_port_shutdown: 8005
    tomcat_port_redirect: 8443
    tomcat_port_ajp: 8009
    tomcat_port_debug: 8000
    tomcat_ajp_enabled: False # Вы можете изменить на True, если требуется AJP
    tomcat_ajp_secret_required: False # Отключение требования секрета для AJP
  roles:
    - role: zaxos.tomcat-ansible-role
